spring.datasource.url=jdbc:postgresql://localhost:5432/modelodslojavirtual
spring.datasource.username=postgres
spring.datasource.password=0000
spring.jpa.hibernate.ddl-auto=update
spring.datasource.platform=postgres
spring.datasource.driver-class-name=org.postgresql.Driver